import * as vscode from 'vscode';
import { Asset, Skill, Agent, Instruction, Workflow, Hook } from '../models/types';
import { AssetLoader } from './assetLoader';

/**
 * Exports Agent Studio assets into GitHub Copilot's native `.github/` structure,
 * following VS Code's custom-instructions conventions: ONE file per asset, named
 * by the asset itself and consolidated into the default flat locations.
 *
 * Layout (keyed by the asset's globally-unique id):
 *   Skill       → .github/prompts/<id>.prompt.md          (reusable prompt)
 *   Workflow    → .github/prompts/<id>.prompt.md          (guided prompt)
 *   Agent       → .github/chatmodes/<id>.chatmode.md      (custom chat mode)
 *   Instruction → .github/instructions/<id>.instructions.md (applyTo from scope)
 *   Hook        → .github/instructions/<id>.instructions.md (applyTo '**')
 *
 * WHY flat-by-asset, not per-marketplace folders: marketplaces are *sources*, but
 * a locally-installed asset is just a local asset. These are VS Code's DEFAULT
 * discovery locations, so a flat tree is the most reliable (no dependence on
 * recursive-subfolder discovery). The registry guarantees unique ids, so there
 * are no in-folder collisions; if two marketplaces share an id, they consolidate
 * to one file (last install wins) — provenance is preserved via the `source`
 * frontmatter key (VS Code ignores unknown keys). We do NOT generate a
 * monolithic `.github/copilot-instructions.md`.
 */
export class CopilotExporter {
  /** Marker we stamp into generated files so we only ever clean up our own output. */
  private static readonly MARKER = '<!-- Generated by Agent Studio -->';

  constructor(private assetLoader: AssetLoader) {}

  /**
   * Export assets to `.github/`.
   *
   * @param activeIds When provided, only assets whose IDs are in this list are
   *                  exported (repo-scoped IDs from ScopeService). When omitted,
   *                  all enabled assets are exported ("export all").
   */
  async exportAll(activeIds?: string[]): Promise<ExportResult> {
    const root = this._getWorkspaceRoot();
    if (!root) {
      return { ok: false, error: 'No workspace folder is open. Open a project first.' };
    }

    const assets = this.assetLoader.getAll().filter((a) => {
      if (a.enabled !== 'enabled') return false;
      if (activeIds) return activeIds.includes(a.id);
      return true;
    });

    const written: string[] = [];
    for (const asset of assets) {
      const path = this.getAssetExportPath(asset);
      const content = this._renderAssetFile(asset);
      if (!path || content === undefined) continue;
      await this._writeNested(root, path, content);
      written.push(path);
    }

    // Reconcile: remove any of OUR previously-generated files that are no longer
    // active (legacy `as-*` flat files, old per-marketplace subfolders, the
    // monolith) so the local set always matches the installed set.
    await this._reconcile(root, new Set(written));
    return { ok: true, written };
  }

  // ── Per-asset install / uninstall ──────────────────────────────────────────

  /**
   * The `.github`-relative path an asset exports to. Every asset type — including
   * hooks — now emits its OWN file (no aggregation), namespaced by marketplace.
   */
  getAssetExportPath(asset: Asset): string | undefined {
    const id = this._slug(asset.id);
    switch (asset.type) {
      case 'skill':       return `.github/prompts/${id}.prompt.md`;
      case 'workflow':    return `.github/prompts/${id}.prompt.md`;
      case 'agent':       return `.github/chatmodes/${id}.chatmode.md`;
      case 'instruction': return `.github/instructions/${id}.instructions.md`;
      case 'hook':        return `.github/instructions/${id}.instructions.md`;
      default:            return undefined;
    }
  }

  /** Write a single asset's file, then reconcile so stale variants are pruned. */
  async exportOne(assetId: string, activeIds: string[]): Promise<ExportResult> {
    const root = this._getWorkspaceRoot();
    if (!root) return { ok: false, error: 'No workspace folder is open.' };

    const asset = this.assetLoader.getById(assetId);
    if (!asset) return { ok: false, error: `Asset "${assetId}" not found.` };

    const path = this.getAssetExportPath(asset);
    const content = this._renderAssetFile(asset);
    if (!path || content === undefined) return { ok: true, written: [] };

    await this._writeNested(root, path, content);
    await this._reconcile(root, this._keepPaths(activeIds));
    return { ok: true, written: [path] };
  }

  /** Remove a single asset's file, then reconcile against the remaining active set. */
  async removeOne(assetId: string, activeIds: string[]): Promise<ExportResult> {
    const root = this._getWorkspaceRoot();
    if (!root) return { ok: false, error: 'No workspace folder is open.' };

    const asset = this.assetLoader.getById(assetId);
    if (!asset) return { ok: false, error: `Asset "${assetId}" not found.` };

    const target = this.getAssetExportPath(asset);
    const removed: string[] = [];
    if (target) {
      try {
        await vscode.workspace.fs.delete(vscode.Uri.joinPath(root, target));
        removed.push(target);
      } catch { /* not present */ }
    }
    // Sweep any legacy/per-marketplace copies of other inactive assets too.
    await this._reconcile(root, this._keepPaths(activeIds.filter((id) => id !== assetId)));
    return { ok: true, written: removed };
  }

  /** The flat target paths of all enabled assets in `activeIds` (the "keep" set). */
  private _keepPaths(activeIds: string[]): Set<string> {
    const keep = new Set<string>();
    for (const a of this.assetLoader.getAll()) {
      if (a.enabled !== 'enabled' || !activeIds.includes(a.id)) continue;
      const p = this.getAssetExportPath(a);
      if (p) keep.add(p);
    }
    return keep;
  }

  /** Render a single asset to its `.github/` file body, or `undefined` if N/A. */
  private _renderAssetFile(asset: Asset): string | undefined {
    switch (asset.type) {
      case 'skill':       return this._buildSkillPrompt(asset);
      case 'workflow':    return this._buildWorkflowPrompt(asset);
      case 'agent':       return this._buildAgentChatmode(asset);
      case 'instruction': return this._buildInstructionFile(asset);
      case 'hook':        return this._buildHookInstruction(asset);
      default:            return undefined;
    }
  }

  // ── File builders ──────────────────────────────────────────────────────────

  /** `.github/prompts/<ns>/<id>.prompt.md` — a reusable Copilot prompt. */
  private _buildSkillPrompt(skill: Skill): string {
    const tools = this._inferTools(skill.tags ?? []);
    const lines: string[] = [
      `---`,
      `mode: 'agent'`,
      `tools: [${tools.map((t) => `'${t}'`).join(', ')}]`,
      `description: '${this._escapeFrontmatter(skill.description)}'`,
      `---`,
      CopilotExporter.MARKER,
      ``,
      `# ${skill.name}`,
      ``,
      `> ${skill.description}`,
      ``,
      `## Instructions`,
      ``,
      skill.systemPrompt.trim(),
      ``,
    ];
    if (skill.bestPractices?.length) {
      lines.push(`## Best Practices`, ``, ...skill.bestPractices.map((p) => `- ${p}`), ``);
    }
    if (skill.userPromptTemplate) {
      lines.push(
        `## How to use`, ``,
        `Provide your code or context below. The following template guides the output:`, ``,
        '```', skill.userPromptTemplate.trim(), '```', ``,
      );
    }
    if (skill.examples?.length) {
      lines.push(`## Examples`, ``);
      for (const ex of skill.examples) lines.push(`**Example input:** ${ex.input}`, ``);
    }
    return lines.join('\n');
  }

  /** `.github/chatmodes/<ns>/<id>.chatmode.md` — a custom Copilot chat mode. */
  private _buildAgentChatmode(agent: Agent): string {
    const agentSkillIds = (agent.capabilities ?? []).flatMap((c) => c.skillIds ?? []);
    const agentSkills = agentSkillIds
      .map((id) => this.assetLoader.getById(id))
      .filter((s): s is Skill => s?.type === 'skill');

    const tools = ['codebase', 'editFiles', 'runCommands', 'search', 'problems'];
    const lines: string[] = [
      `---`,
      `description: '${this._escapeFrontmatter(agent.description)}'`,
      `tools: [${tools.map((t) => `'${t}'`).join(', ')}]`,
      `---`,
      CopilotExporter.MARKER,
      ``,
      `# ${agent.name}`,
      `**Role:** ${agent.role}`,
      ``,
      `## Behaviour`,
      ``,
      agent.systemPrompt.trim(),
      ``,
    ];
    if (agent.capabilities?.length) {
      lines.push(`## Capabilities`, ``);
      for (const cap of agent.capabilities) lines.push(`### ${cap.name}`, cap.description, ``);
    }
    if (agentSkills.length) {
      lines.push(`## Skills available to this agent`, ``);
      for (const skill of agentSkills) lines.push(`### ${skill.name}`, ``, skill.systemPrompt.trim(), ``);
    }
    return lines.join('\n');
  }

  /**
   * `.github/instructions/<ns>/<id>.instructions.md` — auto-injected by Copilot
   * when files matching `applyTo` are active. Global instructions apply to `**`.
   */
  private _buildInstructionFile(inst: Instruction): string {
    let applyTo = '**';
    if (inst.scope === 'language' && inst.languageIds?.length) {
      const exts = inst.languageIds.map((l) => LANG_TO_EXT[l] ?? l).join(',');
      applyTo = `**/*.{${exts}}`;
    }
    return [
      `---`,
      `name: '${this._escapeFrontmatter(inst.name)}'`,
      `description: '${this._escapeFrontmatter(inst.description)}'`,
      `applyTo: '${applyTo}'`,
      ...(inst.marketplaceId ? [`source: '${this._slug(inst.marketplaceId)}'`] : []),
      `---`,
      CopilotExporter.MARKER,
      ``,
      `# ${inst.name}`,
      ``,
      `> ${inst.description}`,
      ``,
      inst.content.trim(),
      ``,
    ].join('\n');
  }

  /**
   * `.github/instructions/<ns>/<id>.hook.instructions.md` — a behavioural rule
   * (formerly aggregated into copilot-instructions.md) as its own always-on
   * instruction file.
   */
  private _buildHookInstruction(hook: Hook): string {
    return [
      `---`,
      `name: '${this._escapeFrontmatter(hook.name)}'`,
      `description: '${this._escapeFrontmatter(hook.description)}'`,
      `applyTo: '**'`,
      ...(hook.marketplaceId ? [`source: '${this._slug(hook.marketplaceId)}'`] : []),
      `---`,
      CopilotExporter.MARKER,
      ``,
      `# ${hook.name}`,
      ``,
      `> ${hook.description}`,
      ``,
      `**Triggers on:** \`${hook.trigger}\`` + (hook.condition ? ` when \`${hook.condition}\`` : ''),
      ``,
      hook.payload.trim(),
      ``,
    ].join('\n');
  }

  /** `.github/prompts/<ns>/<id>.workflow.prompt.md` — a guided multi-step prompt. */
  private _buildWorkflowPrompt(workflow: Workflow): string {
    const lines: string[] = [
      `---`,
      `mode: 'agent'`,
      `tools: ['codebase', 'editFiles', 'runCommands', 'search', 'problems']`,
      `description: '${this._escapeFrontmatter(workflow.description)}'`,
      `---`,
      CopilotExporter.MARKER,
      ``,
      `# Workflow: ${workflow.name}`,
      ``,
      `> ${workflow.description}`,
      ``,
      `**Phases:** ${workflow.phases.join(' → ')}`,
      ``,
      `When this workflow is invoked, work through each phase and step sequentially.`,
      `Complete one step fully before moving to the next. Confirm with the user at phase boundaries.`,
      ``,
    ];

    const phaseOrder: string[] = [];
    const phaseGroups = new Map<string, typeof workflow.steps>();
    for (const step of workflow.steps) {
      if (!phaseGroups.has(step.phase)) { phaseGroups.set(step.phase, []); phaseOrder.push(step.phase); }
      phaseGroups.get(step.phase)!.push(step);
    }
    for (const phase of phaseOrder) {
      lines.push(`## Phase: ${phase.charAt(0).toUpperCase() + phase.slice(1)}`, ``);
      for (const step of phaseGroups.get(phase)!) {
        lines.push(`### Step: ${step.name}`, ``, step.prompt.trim(), ``);
        if (step.agentId) lines.push(`*Handled by agent: \`${step.agentId}\`*`, ``);
      }
      lines.push(`---`, ``);
    }
    return lines.join('\n');
  }

  // ── Helpers ────────────────────────────────────────────────────────────────

  private _slug(s: string): string {
    return s.toLowerCase().replace(/[^a-z0-9._-]+/g, '-').replace(/^-+|-+$/g, '') || 'asset';
  }

  /**
   * Reconcile the local `.github/` asset files with the desired set: delete every
   * file WE generated (or a legacy `as-*` file) that isn't in `keep`, recursively
   * across instructions/prompts/chatmodes, prune emptied folders, and remove the
   * old monolithic copilot-instructions.md. Never touches files we didn't author.
   */
  private async _reconcile(root: vscode.Uri, keep: Set<string>): Promise<void> {
    // Old monolith (only if we generated it).
    const monolith = vscode.Uri.joinPath(root, '.github/copilot-instructions.md');
    try {
      const text = Buffer.from(await vscode.workspace.fs.readFile(monolith)).toString('utf8');
      if (text.includes('Generated by Agent Studio') || text.includes('Repository Copilot Instructions')) {
        await vscode.workspace.fs.delete(monolith);
      }
    } catch { /* absent */ }

    for (const dir of ['.github/instructions', '.github/prompts', '.github/chatmodes']) {
      await this._sweep(root, dir, keep);
    }
  }

  /** Recursively delete our orphaned generated files under `relDir`; prune empty dirs. */
  private async _sweep(root: vscode.Uri, relDir: string, keep: Set<string>): Promise<void> {
    const base = vscode.Uri.joinPath(root, relDir);
    let entries: [string, vscode.FileType][];
    try { entries = await vscode.workspace.fs.readDirectory(base); } catch { return; }

    for (const [name, type] of entries) {
      const rel = `${relDir}/${name}`;
      if (type === vscode.FileType.Directory) {
        await this._sweep(root, rel, keep);
        try {
          const left = await vscode.workspace.fs.readDirectory(vscode.Uri.joinPath(root, rel));
          if (left.length === 0) await vscode.workspace.fs.delete(vscode.Uri.joinPath(root, rel));
        } catch { /* ignore */ }
        continue;
      }
      if (type !== vscode.FileType.File) continue;
      if (keep.has(rel)) continue;
      if (!/\.(instructions|prompt|chatmode)\.md$/.test(name)) continue;

      const isLegacyName = name.startsWith('as-');
      try {
        const text = Buffer.from(await vscode.workspace.fs.readFile(vscode.Uri.joinPath(root, rel))).toString('utf8');
        if (isLegacyName || text.includes(CopilotExporter.MARKER)) {
          await vscode.workspace.fs.delete(vscode.Uri.joinPath(root, rel));
        }
      } catch { /* ignore */ }
    }
  }

  private _inferTools(tags: string[]): string[] {
    const tools = new Set(['codebase']);
    if (tags.some((t) => ['review', 'refactoring', 'implementation', 'fix'].includes(t))) tools.add('editFiles');
    if (tags.some((t) => ['testing', 'tdd', 'lint'].includes(t))) { tools.add('runCommands'); tools.add('problems'); }
    if (tags.some((t) => ['search', 'investigation', 'debugging'].includes(t))) tools.add('search');
    return Array.from(tools);
  }

  private _escapeFrontmatter(str: string): string {
    return str.replace(/'/g, "\\'").replace(/\n/g, ' ').slice(0, 120);
  }

  private _getWorkspaceRoot(): vscode.Uri | undefined {
    return vscode.workspace.workspaceFolders?.[0]?.uri;
  }

  /** Write a file, creating any parent folders (so per-marketplace dirs appear). */
  private async _writeNested(root: vscode.Uri, relativePath: string, content: string): Promise<void> {
    const uri = vscode.Uri.joinPath(root, relativePath);
    const dir = vscode.Uri.joinPath(uri, '..');
    try { await vscode.workspace.fs.createDirectory(dir); } catch { /* exists */ }
    await vscode.workspace.fs.writeFile(uri, Buffer.from(content, 'utf-8'));
  }
}

export interface ExportResult {
  ok: boolean;
  written?: string[];
  error?: string;
}

const LANG_TO_EXT: Record<string, string> = {
  typescript: 'ts',
  typescriptreact: 'tsx',
  javascript: 'js',
  javascriptreact: 'jsx',
  python: 'py',
  go: 'go',
  rust: 'rs',
  java: 'java',
  csharp: 'cs',
  cpp: 'cpp',
  c: 'c',
  ruby: 'rb',
  php: 'php',
  swift: 'swift',
  kotlin: 'kt',
};
