import * as vscode from 'vscode';
import { Asset, Skill, Agent, Instruction, Workflow, Hook } from '../models/types';
import { AssetLoader } from './assetLoader';

/**
 * Exports Agent Studio assets into GitHub Copilot's native `.github/` structure,
 * following VS Code's custom-instructions conventions: ONE file per asset,
 * organized into per-marketplace folders so nothing bloats a single file.
 *
 * Layout (ns = the asset's marketplaceId, or "agent-studio" when unknown):
 *   Skill       → .github/prompts/<ns>/<id>.prompt.md          (reusable prompt)
 *   Workflow    → .github/prompts/<ns>/<id>.workflow.prompt.md  (guided prompt)
 *   Agent       → .github/chatmodes/<ns>/<id>.chatmode.md       (custom chat mode)
 *   Instruction → .github/instructions/<ns>/<id>.instructions.md (applyTo glob)
 *   Hook        → .github/instructions/<ns>/<id>.hook.instructions.md (applyTo '**')
 *
 * VS Code searches these folders recursively, and each instruction file's
 * `applyTo` is relative to the workspace root — so per-marketplace subfolders are
 * safe and keep one team's/plugin's assets cleanly grouped. We deliberately do
 * NOT generate a monolithic `.github/copilot-instructions.md`; a previously
 * generated one is removed on the next export (see _cleanupLegacy).
 */
export class CopilotExporter {
  /** Marker we stamp into generated files so we only ever clean up our own output. */
  private static readonly MARKER = '<!-- Generated by Agent Studio -->';

  constructor(private assetLoader: AssetLoader) {}

  /**
   * Export assets to `.github/`.
   *
   * @param activeIds When provided, only assets whose IDs are in this list are
   *                  exported (repo-scoped IDs from ScopeService). When omitted,
   *                  all enabled assets are exported ("export all").
   */
  async exportAll(activeIds?: string[]): Promise<ExportResult> {
    const root = this._getWorkspaceRoot();
    if (!root) {
      return { ok: false, error: 'No workspace folder is open. Open a project first.' };
    }

    const assets = this.assetLoader.getAll().filter((a) => {
      if (a.enabled !== 'enabled') return false;
      if (activeIds) return activeIds.includes(a.id);
      return true;
    });

    // Migrate away from the old monolith + flat `as-*` files before re-exporting.
    await this._cleanupLegacy(root);

    const written: string[] = [];
    for (const asset of assets) {
      const path = this.getAssetExportPath(asset);
      const content = this._renderAssetFile(asset);
      if (!path || content === undefined) continue;
      await this._writeNested(root, path, content);
      written.push(path);
    }

    return { ok: true, written };
  }

  // ── Per-asset install / uninstall ──────────────────────────────────────────

  /**
   * The `.github`-relative path an asset exports to. Every asset type — including
   * hooks — now emits its OWN file (no aggregation), namespaced by marketplace.
   */
  getAssetExportPath(asset: Asset): string | undefined {
    const ns = this._namespace(asset);
    switch (asset.type) {
      case 'skill':       return `.github/prompts/${ns}/${asset.id}.prompt.md`;
      case 'workflow':    return `.github/prompts/${ns}/${asset.id}.workflow.prompt.md`;
      case 'agent':       return `.github/chatmodes/${ns}/${asset.id}.chatmode.md`;
      case 'instruction': return `.github/instructions/${ns}/${asset.id}.instructions.md`;
      case 'hook':        return `.github/instructions/${ns}/${asset.id}.hook.instructions.md`;
      default:            return undefined;
    }
  }

  /** Write a single asset's file. No aggregated file to keep in sync anymore. */
  async exportOne(assetId: string, _activeIds: string[]): Promise<ExportResult> {
    const root = this._getWorkspaceRoot();
    if (!root) return { ok: false, error: 'No workspace folder is open.' };

    const asset = this.assetLoader.getById(assetId);
    if (!asset) return { ok: false, error: `Asset "${assetId}" not found.` };

    const path = this.getAssetExportPath(asset);
    const content = this._renderAssetFile(asset);
    if (!path || content === undefined) return { ok: true, written: [] };

    await this._writeNested(root, path, content);
    return { ok: true, written: [path] };
  }

  /** Remove a single asset's file (tries the current and legacy flat paths). */
  async removeOne(assetId: string, _activeIds: string[]): Promise<ExportResult> {
    const root = this._getWorkspaceRoot();
    if (!root) return { ok: false, error: 'No workspace folder is open.' };

    const asset = this.assetLoader.getById(assetId);
    if (!asset) return { ok: false, error: `Asset "${assetId}" not found.` };

    const removed: string[] = [];
    for (const path of [this.getAssetExportPath(asset), ...this._legacyPaths(asset)]) {
      if (!path) continue;
      try {
        await vscode.workspace.fs.delete(vscode.Uri.joinPath(root, path));
        removed.push(path);
      } catch { /* not present */ }
    }
    return { ok: true, written: removed };
  }

  /** Render a single asset to its `.github/` file body, or `undefined` if N/A. */
  private _renderAssetFile(asset: Asset): string | undefined {
    switch (asset.type) {
      case 'skill':       return this._buildSkillPrompt(asset);
      case 'workflow':    return this._buildWorkflowPrompt(asset);
      case 'agent':       return this._buildAgentChatmode(asset);
      case 'instruction': return this._buildInstructionFile(asset);
      case 'hook':        return this._buildHookInstruction(asset);
      default:            return undefined;
    }
  }

  // ── File builders ──────────────────────────────────────────────────────────

  /** `.github/prompts/<ns>/<id>.prompt.md` — a reusable Copilot prompt. */
  private _buildSkillPrompt(skill: Skill): string {
    const tools = this._inferTools(skill.tags ?? []);
    const lines: string[] = [
      `---`,
      `mode: 'agent'`,
      `tools: [${tools.map((t) => `'${t}'`).join(', ')}]`,
      `description: '${this._escapeFrontmatter(skill.description)}'`,
      `---`,
      CopilotExporter.MARKER,
      ``,
      `# ${skill.name}`,
      ``,
      `> ${skill.description}`,
      ``,
      `## Instructions`,
      ``,
      skill.systemPrompt.trim(),
      ``,
    ];
    if (skill.bestPractices?.length) {
      lines.push(`## Best Practices`, ``, ...skill.bestPractices.map((p) => `- ${p}`), ``);
    }
    if (skill.userPromptTemplate) {
      lines.push(
        `## How to use`, ``,
        `Provide your code or context below. The following template guides the output:`, ``,
        '```', skill.userPromptTemplate.trim(), '```', ``,
      );
    }
    if (skill.examples?.length) {
      lines.push(`## Examples`, ``);
      for (const ex of skill.examples) lines.push(`**Example input:** ${ex.input}`, ``);
    }
    return lines.join('\n');
  }

  /** `.github/chatmodes/<ns>/<id>.chatmode.md` — a custom Copilot chat mode. */
  private _buildAgentChatmode(agent: Agent): string {
    const agentSkillIds = (agent.capabilities ?? []).flatMap((c) => c.skillIds ?? []);
    const agentSkills = agentSkillIds
      .map((id) => this.assetLoader.getById(id))
      .filter((s): s is Skill => s?.type === 'skill');

    const tools = ['codebase', 'editFiles', 'runCommands', 'search', 'problems'];
    const lines: string[] = [
      `---`,
      `description: '${this._escapeFrontmatter(agent.description)}'`,
      `tools: [${tools.map((t) => `'${t}'`).join(', ')}]`,
      `---`,
      CopilotExporter.MARKER,
      ``,
      `# ${agent.name}`,
      `**Role:** ${agent.role}`,
      ``,
      `## Behaviour`,
      ``,
      agent.systemPrompt.trim(),
      ``,
    ];
    if (agent.capabilities?.length) {
      lines.push(`## Capabilities`, ``);
      for (const cap of agent.capabilities) lines.push(`### ${cap.name}`, cap.description, ``);
    }
    if (agentSkills.length) {
      lines.push(`## Skills available to this agent`, ``);
      for (const skill of agentSkills) lines.push(`### ${skill.name}`, ``, skill.systemPrompt.trim(), ``);
    }
    return lines.join('\n');
  }

  /**
   * `.github/instructions/<ns>/<id>.instructions.md` — auto-injected by Copilot
   * when files matching `applyTo` are active. Global instructions apply to `**`.
   */
  private _buildInstructionFile(inst: Instruction): string {
    let applyTo = '**';
    if (inst.scope === 'language' && inst.languageIds?.length) {
      const exts = inst.languageIds.map((l) => LANG_TO_EXT[l] ?? l).join(',');
      applyTo = `**/*.{${exts}}`;
    }
    return [
      `---`,
      `name: '${this._escapeFrontmatter(inst.name)}'`,
      `description: '${this._escapeFrontmatter(inst.description)}'`,
      `applyTo: '${applyTo}'`,
      `---`,
      CopilotExporter.MARKER,
      ``,
      `# ${inst.name}`,
      ``,
      `> ${inst.description}`,
      ``,
      inst.content.trim(),
      ``,
    ].join('\n');
  }

  /**
   * `.github/instructions/<ns>/<id>.hook.instructions.md` — a behavioural rule
   * (formerly aggregated into copilot-instructions.md) as its own always-on
   * instruction file.
   */
  private _buildHookInstruction(hook: Hook): string {
    return [
      `---`,
      `name: '${this._escapeFrontmatter(hook.name)}'`,
      `description: '${this._escapeFrontmatter(hook.description)}'`,
      `applyTo: '**'`,
      `---`,
      CopilotExporter.MARKER,
      ``,
      `# ${hook.name}`,
      ``,
      `> ${hook.description}`,
      ``,
      `**Triggers on:** \`${hook.trigger}\`` + (hook.condition ? ` when \`${hook.condition}\`` : ''),
      ``,
      hook.payload.trim(),
      ``,
    ].join('\n');
  }

  /** `.github/prompts/<ns>/<id>.workflow.prompt.md` — a guided multi-step prompt. */
  private _buildWorkflowPrompt(workflow: Workflow): string {
    const lines: string[] = [
      `---`,
      `mode: 'agent'`,
      `tools: ['codebase', 'editFiles', 'runCommands', 'search', 'problems']`,
      `description: '${this._escapeFrontmatter(workflow.description)}'`,
      `---`,
      CopilotExporter.MARKER,
      ``,
      `# Workflow: ${workflow.name}`,
      ``,
      `> ${workflow.description}`,
      ``,
      `**Phases:** ${workflow.phases.join(' → ')}`,
      ``,
      `When this workflow is invoked, work through each phase and step sequentially.`,
      `Complete one step fully before moving to the next. Confirm with the user at phase boundaries.`,
      ``,
    ];

    const phaseOrder: string[] = [];
    const phaseGroups = new Map<string, typeof workflow.steps>();
    for (const step of workflow.steps) {
      if (!phaseGroups.has(step.phase)) { phaseGroups.set(step.phase, []); phaseOrder.push(step.phase); }
      phaseGroups.get(step.phase)!.push(step);
    }
    for (const phase of phaseOrder) {
      lines.push(`## Phase: ${phase.charAt(0).toUpperCase() + phase.slice(1)}`, ``);
      for (const step of phaseGroups.get(phase)!) {
        lines.push(`### Step: ${step.name}`, ``, step.prompt.trim(), ``);
        if (step.agentId) lines.push(`*Handled by agent: \`${step.agentId}\`*`, ``);
      }
      lines.push(`---`, ``);
    }
    return lines.join('\n');
  }

  // ── Helpers ────────────────────────────────────────────────────────────────

  /** Per-asset folder: the marketplace it came from, or a stable default. */
  private _namespace(asset: Asset): string {
    return this._slug(asset.marketplaceId || 'agent-studio');
  }

  private _slug(s: string): string {
    return s.toLowerCase().replace(/[^a-z0-9._-]+/g, '-').replace(/^-+|-+$/g, '') || 'agent-studio';
  }

  /** Pre-refactor flat paths, tried on uninstall so old installs clean up too. */
  private _legacyPaths(asset: Asset): string[] {
    switch (asset.type) {
      case 'skill':       return [`.github/prompts/as-skill-${asset.id}.prompt.md`];
      case 'workflow':    return [`.github/prompts/as-workflow-${asset.id}.prompt.md`];
      case 'agent':       return [`.github/chatmodes/as-agent-${asset.id}.chatmode.md`];
      case 'instruction': return [`.github/instructions/as-inst-${asset.id}.instructions.md`];
      default:            return [];
    }
  }

  /** Remove the old monolithic copilot-instructions.md (only if WE generated it). */
  private async _cleanupLegacy(root: vscode.Uri): Promise<void> {
    const legacy = vscode.Uri.joinPath(root, '.github/copilot-instructions.md');
    try {
      const buf = await vscode.workspace.fs.readFile(legacy);
      const text = Buffer.from(buf).toString('utf8');
      if (text.includes('Generated by Agent Studio') || text.includes('Repository Copilot Instructions')) {
        await vscode.workspace.fs.delete(legacy);
      }
    } catch { /* not present — fine */ }
  }

  private _inferTools(tags: string[]): string[] {
    const tools = new Set(['codebase']);
    if (tags.some((t) => ['review', 'refactoring', 'implementation', 'fix'].includes(t))) tools.add('editFiles');
    if (tags.some((t) => ['testing', 'tdd', 'lint'].includes(t))) { tools.add('runCommands'); tools.add('problems'); }
    if (tags.some((t) => ['search', 'investigation', 'debugging'].includes(t))) tools.add('search');
    return Array.from(tools);
  }

  private _escapeFrontmatter(str: string): string {
    return str.replace(/'/g, "\\'").replace(/\n/g, ' ').slice(0, 120);
  }

  private _getWorkspaceRoot(): vscode.Uri | undefined {
    return vscode.workspace.workspaceFolders?.[0]?.uri;
  }

  /** Write a file, creating any parent folders (so per-marketplace dirs appear). */
  private async _writeNested(root: vscode.Uri, relativePath: string, content: string): Promise<void> {
    const uri = vscode.Uri.joinPath(root, relativePath);
    const dir = vscode.Uri.joinPath(uri, '..');
    try { await vscode.workspace.fs.createDirectory(dir); } catch { /* exists */ }
    await vscode.workspace.fs.writeFile(uri, Buffer.from(content, 'utf-8'));
  }
}

export interface ExportResult {
  ok: boolean;
  written?: string[];
  error?: string;
}

const LANG_TO_EXT: Record<string, string> = {
  typescript: 'ts',
  typescriptreact: 'tsx',
  javascript: 'js',
  javascriptreact: 'jsx',
  python: 'py',
  go: 'go',
  rust: 'rs',
  java: 'java',
  csharp: 'cs',
  cpp: 'cpp',
  c: 'c',
  ruby: 'rb',
  php: 'php',
  swift: 'swift',
  kotlin: 'kt',
};
